from typing import Any, Protocol, TypeVar, runtime_checkable


@runtime_checkable
class ArrayLike(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> Any: ...

    def __getitem__(self, index: Any) -> Any: ...
    def __len__(self) -> int: ...

    # arithmetic
    def __add__(self, other: Any) -> "ArrayLike": ...
    def __sub__(self, other: Any) -> "ArrayLike": ...
    def __mul__(self, other: Any) -> "ArrayLike": ...
    def __truediv__(self, other: Any) -> "ArrayLike": ...
    def __matmul__(self, other: Any) -> "ArrayLike": ...
    def __neg__(self) -> "ArrayLike": ...


A = TypeVar("A", bound=ArrayLike)
